@BASE_URL = http://localhost:8080/daeProjeto/api
@TOKEN = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJjb2xhYkBtYWlsLnB0IiwiaWF0IjoxNzY5MTg2MzE1LCJleHAiOjE3NjkxODk5MTV9.AY8_j7d8siiqUmMGOI_AFJ_FzKb0RSrG74xW6K_aLaQHhptZqLUgTW2Ln9cFu-OA

###EP38. Get recommended publications
GET {{BASE_URL}}/publications/recommended
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###EP42. Get publications by area
GET {{BASE_URL}}/statistics/publications-by-area
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###EP43. Get average rating by area
GET {{BASE_URL}}/statistics/average-rating-by-area
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###EP44. Get average rating by tag
GET {{BASE_URL}}/statistics/average-rating-by-tag
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###EP45. Get submissions by day
GET {{BASE_URL}}/statistics/evolution-submissions
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###EP46. Get notifications
GET {{BASE_URL}}/notifications
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
